### ISSUE TITLE
Can't use extension when using multiple folder inside workspace

### ISSUE THREAD

**Issue by AngDrew** [mikededo/dartBarrelFileGenerator#102]
I can't use the extension when having many folders on my vscode workspace
step to reproduce:
1. open project folder
2. add other folder to workspace: file > add folder to workspace
3. save the workspace as vscode workspace: file > save workspace as
4. right click on one of the workspaces, generate barrel import
5. GDBF: Error on generating the file

logger:
```[2023-11-14 06:53:19] Generation started 2023-11-14 06:53:19
[2023-11-14 06:53:19] Type: recursive - Path: c:\Users\my.username\Documents\projects\flutter-project\my_app\lib\modules\my_module
[2023-11-14 06:53:19] ERROR: Error: Select a folder from the workspace
[2023-11-14 06:53:19] Elapsed time: 1ms

**Comment by mikededo** [comment]
Hey @AngDrew, thanks for opening an issue 👋🏼!

Currently this is a limitation of the extension and I have not planned on working on this since I had many issues when I tried. If I ever find a proper solution, I would let you know. Otherwise, it is not possible now to execute the extension in VSCode workspaces.
