### ISSUE TITLE
using excludeFileList to exclude main.dart

### ISSUE THREAD

**Issue by matthewkooshad** [mikededo/dartBarrelFileGenerator#103]
i'm trying to ignore main.dart that's in lib folder. when i try to barrel the lib folder, it's not working. what should i put for the value below? thanks

"dartBarrelFileGenerator.excludeFileList": [
        "main.dart"
    ],

**Comment by mikededo** [comment]
Hey @matthewkooshad, sorry for the late reply, I barely have time to keep up.

Were you able to solve the issue? If not, let me know and I'll dig into it.

**Comment by matthewkooshad** [comment]
it is not solved for me; i am still seeing `export 'main.dart';` in my lib.dart barrel file undesirably.

**Comment by mikededo** [comment]
Hey @matthewkooshad. In order to check which files are excluded or not, the extension uses [glob](https://www.npmjs.com/package/glob). In this case, by using only `main.dart`, files that are within a nested folder will not be excluded. Therefore, you should add the `**/` glob before (use `**/main.dart` instead of `main.dart`).  
Now, file patterns like `./src/lib/main.dart` will also be matched with `**/main.dart`.

Sorry for your waiting. Feel free to comment and reopen this issue if it is still happening.
