### ISSUE TITLE
Files excluded unexpectedly

### ISSUE THREAD

**Issue by witchdrash** [mikededo/dartBarrelFileGenerator#21]
We have the following file structure
- scaffolding
- - large_scaffolding.dart
- - small_scaffolding.dart
- - top_nav_bar.dart
- - bottom_information_bar.dart

When using the plug in the large and small scaffolding files are unexpectedly excluded from the barrel, file, removing the word scaffolding makes them appear, removing it makes them disappear, there's nothing in the documentation that suggests this is expected behaviour

**Comment by mikededo** [comment]
Hi @witchdrash, thanks for opening an issue 😄 

Could you please check your Visual Studio Code settings (pressing <kbd>F1</kbd> and typing`Preferences: Open Settings (JSON)`) and search for the setting with name: `dartBarrelFileGenerator.excludeFileList` (if you are accessing your settings through the UI, search for `Dart Barrel File Generator: Exclude File List`). Could it be that you have defined a blob that matches the `scaffolding` pattern?

**Comment by witchdrash** [comment]
This is my entire settings file:
`{
    "editor.formatOnSave": true,
    "editor.minimap.maxColumn": 999999,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            120
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.debugExternalPackageLibraries": false,
    "dart.debugSdkLibraries": false,
    "dart.lineLength": 120,
    "workbench.colorTheme": "Monokai",
    "dart.warnWhenEditingFilesOutsideWorkspace": false,
    "editor.wordWrapColumn": 80,
    "files.autoSave": "afterDelay"
}`

**Comment by mikededo** [comment]
Okey, I will try to recreate it as soon as I have time!

**Comment by witchdrash** [comment]
My guess would be that this function:

`export const isBarrelFile = (dirName: string, fileName: string) =>
  FILE_REGEX.base(dirName).test(fileName);`

Is matching on partials as well as complete names

**Comment by mikededo** [comment]
Yep, that is it. The barrel file is named after the folder name, which would be `scaffolding.dart` in your case. Since the files have the `scaffoling` naming, it is what causes the issues.

As soon as I can I will work on a fix, which should not be much of a deal. Thanks for your patience! ✌🏼

**Comment by mikededo** [comment]
Hi @witchdrash! I've been digging a bit more in what was the problem, and unluckily it was not the `isBarrelFile` function. The functions does as it should, since it adds the characted `^` at the [begginning of the RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet#boundary-type_assertions).

What is causing the issue is the RegExp that checks whether a file extends a suffix or not. The RegExp is the following: `.*(.${suffix}.dart)$`. The issue is with the second dot, as it is not scaped, when my intentions are the dot to be a character. Therefore, it has to be scaped. The fixed RegExp will be: `(\.${suffix}.dart)$`. 

I will post an update soon. Thanks for reporting the issue! 😃
