### ISSUE TITLE
Option for default name of barrel files

### ISSUE THREAD

**Issue by DFelten** [mikededo/dartBarrelFileGenerator#54]
Could you maybe add the possibility to change the default name of a barrel file? 

I would like to call each barrel file for example `index.dart`. Currently, a created file overwrites the existing files if they are named exactly like the folder. So index.dart is a good default for us.

**Comment by mikededo** [comment]
Thanks @DFelten for opening the issue 😄!

Adding an option in the user settings that allows you to _always_ name the file differently (instead of the default `<folder-name>.dart`). There is currently [this option](https://github.com/mikededo/dartBarrelFileGenerator/blob/78277c1de136d473a5cde299764f9f413654d9fd/package.json#L54) that, when "on" and you create a barrel file an input appears. This is more like a one-time use case, and if you say you _always_ use `index.dart`, then sure having a default is better.

As soon as I can I will get into it!

**Comment by DFelten** [comment]
Thanks! As far as I know The problem with the current option is that this is only working for one folder and not for nested ones.

So when adding the prompt also for nested folders would also be a great improvement. 

But a default is at least for me the best solution :)

**Comment by mikededo** [comment]
Oh! Thanks for pointing it out! I will address both issues as it is not the expected behaviour! 👀

**Comment by mikededo** [comment]
I have been revising the code, and we decided that we would not implement the custom "renaming" of files when `current and nested` generation was chosen (see [here](https://github.com/mikededo/dartBarrelFileGenerator/issues/16#issuecomment-1002212627)).

As I nobody required such feature, I decided not to implement it. However, I will add it 👍🏼

**Comment by DFelten** [comment]
Thanks, that would be great!

**Comment by mikededo** [comment]
Issue solved in #58! It will be available in the next release 🥳

**Comment by mikededo** [comment]
Feature added in `v4.0.0` which should be life now! Thank you for your proposal, give me any feedback you can 💪🏼!

Star the project and recommend it to your fellow developers to help the extension grow 😄
