### ISSUE TITLE
glob patterns not matching as expected

### ISSUE THREAD

**Issue by mrgnhnt96** [mikededo/dartBarrelFileGenerator#89]
Within the setting `excludeDirList`, I have added the glob pattern `"**/screens/**components/**". When I run either the "current folder with nested folders" or the "current with subfolders" commands, I get barrel files that should've been excluded according to the glob pattern.

I verified that the glob pattern is correct using [the glob tool](https://t.ly/9LLy).

A work around at the moment is only specify the folder name, such as `components`. This generates the expected output except this includes _all_ components folders, which is **not** desired.

I tried `**/screens/**/components/**/*.dart` within the `excludeFileList` and got the same result (where the file path doesn't match the glob pattern). Though, `**/*.g.dart` continues to work as successful glob pattern.

**Comment by mikededo** [comment]
Welcome back @mrgnhnt96 💪

Right, the other day is was thinking that the docs are not entirely correct, as the lib that it is used is `minimatch`, which may be the reaason why it is causing issues. I'm kind of busy lately, but I will look into it!

**Comment by mrgnhnt96** [comment]
👋

Gotcha! That makes more sense. I think it would be great to support glob patterns for directories, it'd make the tool way more robust 💪 

Thanks for continuing to maintain the package! I use it a ton! With that said, get to it when you can, no pressure

**Comment by mikededo** [comment]
It really fullfills me to know that this is _that_ useful to someone!

Could it be possible for you to provide me with your file structure, the minimum, so I can recreate it? Or if you have an open sourced project.

**Comment by mikededo** [comment]
> Please, if I have not understood your problem correctly, tell me!!

So, I have been trying to recreate the issue, since the library should work as any other, as it is the library used by `npm` itself. I have recreated the following structure:

```sh
.
└── domain
    ├── screens
    │   ├── auth
    │   │   ├── components
    │   │   │   └── excluded.dart *
    │   │   └── services
    │   │       └── included.dart
    │   └── dashboard
    │       ├── components
    │       │   └── excluded.dart *
    │       └── services
    │           └── services.dart
    └── shared
        └── shared.dart
```

I think I have been able to some-how recreate your problem. In this, the files named `excluded.dart`, are those that you do not want to export them (am I right?). Now, here are the patterns that I have tried, when running `Current with subfolders` (for the path: `/<other-folders>/domain/screens/dashboard/services`):

- <code>\*\*/screens/\*\*/components/\*\*</code> -> `false`
- <code>\*\*/screens/\*\*/components/</code> -> `false`
- <code>\*\*/screens/\*\*/components</code> -> `true`

So, what are the issues that I have found?

- First, I was not passing the `whole` glob file to the `matchesGlob` function, rather the last folder name. So, for the path of the example, instead of passing the entire path, I was only passing `services`. Therefore, complex examples as your would never work.
- Secondly, which it is quite hard to decide if it is something the extension should handle, or something to define as a design decision, and users should adapt to it. The thing is that the I am not appending a `/` to the path passed to `matchesGlob`, which is the reason why the 3rd case passes, but does not the second.

Then, I have given a couple thoughts about it:

- There's obviously a bug by not passing the entire path to the `matchesGlob` function. This will be fixed asap.
- I will most likely update the documentation explaining that directory patterns **should be as the third** case scenario (I will look for more edge cases), instead of the first or second.

I will try to work on it when possible! Expect to have it done by the end of the week 🚢

**Comment by mrgnhnt96** [comment]
That is essentially the folder structure that I have 👍 

> There's obviously a bug by not passing the entire path to the matchesGlob function. This will be fixed asap.

This would be perfect! This is how I would expect the project to work

> I will most likely update the documentation explaining that directory patterns should be as the third case scenario (I will look for more edge cases), instead of the first or second.

I agree that this should be a teaching/doc strategy vs functionality. Though, I think it could be trivial to handle. What if you checked for an appended `/` or `/**` and removed it before you ran the command? If you ended up doing this, you can still instruct for the pattern to match the third case and handle the use cases if they don't.

The regex to check for any appended `/`, `\`, and `*` is: 

```regex
[\/\\*]+$
```
