### ISSUE TITLE
Add support for `always_use_package_imports`

### ISSUE THREAD

**Issue by mbfakourii** [mikededo/dartBarrelFileGenerator#97]
Hi, please support the [`always_use_package_imports`](https://dart.dev/tools/linter-rules/always_use_package_imports) rule.

**Comment by mikededo** [comment]
Hi @mbfakourii 👋🏼! Thanks for opening an issue. I have stopped using Dart and I'm no longer familiarised with the linter. However, from what I understand about this rule, would consist on adding `package:{packageName}` as a prefix of the import, right?

Should this only work for the root barrel file? I mean, should this `package:{packageName}` prefix be added for a barrel file that is, for example, 3 folders deep? Or it should only be added to the top of the folder? Also, I would have to somehow get the `packageName` from the `pubspec.yaml` file, somehow, and I'm not really sure if that would be possible.

Nonetheless, I see that the linter has a quick fix for this issue, so if it is a bit of a mess to develop, I would suggest running the linter (maybe I can run it using VSCode's API) in order to fix it.

**Comment by mikededo** [comment]
So I understand this would ONLY happen for the barrel file that is at the root of the project, this being `./lib/<filename>.dart`, right?

**Comment by mbfakourii** [comment]
> So I understand this would ONLY happen for the barrel file that is at the root of the project, this being `./lib/<filename>.dart`, right?

yes

**Comment by mikededo** [comment]
Sorry for the delay. Currently I'm a bit tight on time and can barely work on the weekends. I'm working on it.

**Comment by mikededo** [comment]
This is solved with the `v6.2.0`. You simply have to enable the option: `dartBarrelFileGenerator.prependPackageToLibExport`.
